Fix Windows VS Code Test Runs and upgrade GDB to 12.1 (#1319)
Windows VS Code tests were failing when falling back to 10.x.

When upgrading to 12.x, GDB was failing because a shared library could not be found and it would error with:

> ERROR: Unable to start debugging. Unexpected GDB output from command \"-exec-run\". During startup program exited with code 0xc0000139

In this PR, the changes made are:
1. Delete downgrade of GDB.
2. Added `inherit` for environment variables so we can use `dotnet` in `MSYS` shell.
3. Converted windows paths needed for `dotnet test` with `cygpath -u` to convert to unix styled paths.
4. Upgrades the version of GNU Compiler and GDB to `12.1`